services:
  stalwart-mail:
    image: stalwartlabs/stalwart:latest-alpine # for production choose specific version from https://hub.docker.com/r/stalwartlabs/stalwart/tags
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "143:143"
      - "993:993"
      - "4190:4190"
      - "8083:8080"
      - "110:110"    # POP3
      - "995:995"    # POP3S
    volumes:
      - stalwart_data:/opt/stalwart-mail
      - ./config:/etc/stalwart:rw
    environment:
      - TZ=${TZ}
      - STALWART_RECOVERY_ADMIN=${STALWART_RECOVERY_ADMIN}
    restart: unless-stopped

volumes:
  stalwart_data: