[storage]
data = "rocksdb"

[store."rocksdb"]
type = "rocksdb"
path = "/opt/stalwart-mail/data"

[server]
hostname = "mail.techvision.edu.et"

[listener."smtp"]
bind = "[::]:25"

[listener."submission"]
bind = "[::]:587"

[listener."smtps"]
bind = "[::]:465"

[listener."imap"]
bind = "[::]:143"

[listener."imaps"]
bind = "[::]:993"

[listener."http"]
bind = "[::]:8080"